### ISSUE TITLE
testing webhooks

### ISSUE THREAD

**Issue by ahadjithoma** [andreash92/andreasBot#3]
2017-06-21T11:38:44.865083+00:00 app[web.1]:   at /app/node_modules/ws/lib/Receiver.js:508:14
2017-06-21T11:38:44.865084+00:00 app[web.1]:   at Receiver.flush (/app/node_modules/ws/lib/Receiver.js:347:3)
2017-06-21T11:38:44.865085+00:00 app[web.1]:   at Receiver.finish (/app/node_modules/ws/lib/Receiver.js:541:12)
2017-06-21T11:38:44.865085+00:00 app[web.1]:   at Receiver.expectHandler (/app/node_modules/ws/lib/Receiver.js:499:31)
2017-06-21T11:38:44.865086+00:00 app[web.1]:   at Receiver.add (/app/node_modules/ws/lib/Receiver.js:103:24)
2017-06-21T11:38:44.865086+00:00 app[web.1]:   at TLSSocket.realHandler (/app/node_modules/ws/lib/WebSocket.js:825:20)
2017-06-21T11:38:44.865087+00:00 app[web.1]:   at emitOne (events.js:96:13)
2017-06-21T11:38:44.865088+00:00 app[web.1]:   at TLSSocket.emit (events.js:188:7)
2017-06-21T11:38:44.865088+00:00 app[web.1]:   at readableAddChunk (_stream_readable.js:176:18)
2017-06-21T11:38:44.865089+00:00 app[web.1]:   at TLSSocket.Readable.push (_stream_readable.js:134:10)
2017-06-21T11:38:44.865089+00:00 app[web.1]:   at TLSWrap.onread (net.js:547:20)
2017-06-21T11:38:44.865090+00:00 app[web.1]: 
2017-06-21T11:38:47.640935+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=96edb119-22f2-415d-a11b-f6c344e01beb fwd="192.30.252.34" dyno= connect= service= status=503 bytes= protocol=https
2017-06-21T11:38:52.429688+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=66405590-0fb3-4d95-b386-5ce798922905 fwd="192.30.252.42" dyno= connect= service= status=503 bytes= protocol=https
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-06-21T11:38:44.865085+00:00 app[web.1]:   at Receiver.expectHandler (/app/node_modules/ws/lib/Receiver.js:499:31)
2017-06-21T11:38:44.865086+00:00 app[web.1]:   at Receiver.add (/app/node_modules/ws/lib/Receiver.js:103:24)
2017-06-21T11:38:44.865086+00:00 app[web.1]:   at TLSSocket.realHandler (/app/node_modules/ws/lib/WebSocket.js:825:20)
2017-06-21T11:38:44.865087+00:00 app[web.1]:   at emitOne (events.js:96:13)
2017-06-21T11:38:44.865088+00:00 app[web.1]:   at TLSSocket.emit (events.js:188:7)
2017-06-21T11:38:44.865088+00:00 app[web.1]:   at readableAddChunk (_stream_readable.js:176:18)
2017-06-21T11:38:44.865089+00:00 app[web.1]:   at TLSSocket.Readable.push (_stream_readable.js:134:10)
2017-06-21T11:38:44.865089+00:00 app[web.1]:   at TLSWrap.onread (net.js:547:20)
2017-06-21T11:38:44.865090+00:00 app[web.1]: 
2017-06-21T11:38:47.640935+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=96edb119-22f2-415d-a11b-f6c344e01beb fwd="192.30.252.34" dyno= connect= service= status=503 bytes= protocol=https
2017-06-21T11:38:52.429688+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=66405590-0fb3-4d95-b386-5ce798922905 fwd="192.30.252.42" dyno= connect= service= status=503 bytes= protocol=https
2017-06-21T11:39:43.595889+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=c9572f56-0336-4b33-898f-d93da393cefb fwd="192.30.252.42" dyno= connect= service= status=503 bytes= protocol=https
2017-06-21T11:40:04.272920+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=f28ec7d4-5f15-47b7-8966-dbd35ae2b03b fwd="192.30.252.41" dyno= connect= service= status=503 bytes= protocol=https
2017-06-21T11:40:04.000000+00:00 app[api]: Build started by user andreas_h92@outlook.com
2017-06-21T11:40:04.646835+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=1460c18c-2115-4de3-b44f-8f6d16825517 fwd="192.30.252.42" dyno= connect= service= status=503 bytes= protocol=https
2017-06-21T11:40:22.090281+00:00 app[api]: Release v506 created by user andreas_h92@outlook.com
2017-06-21T11:40:22.090281+00:00 app[api]: Deploy c089a63c by user andreas_h92@outlook.com
2017-06-21T11:40:04.000000+00:00 app[api]: Build succeeded
2017-06-21T11:40:22.942701+00:00 heroku[web.1]: State changed from crashed to starting
2017-06-21T11:40:23.120841+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=1a561b10-9a20-447e-98fa-3e824f85309e fwd="192.30.252.45" dyno= connect= service= status=503 bytes= protocol=https
2017-06-21T11:40:25.938565+00:00 heroku[web.1]: Starting process with command `bin/hubot -a slack`
2017-06-21T11:40:36.077554+00:00 heroku[web.1]: State changed from starting to up
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-06-21T11:40:38.305634+00:00 app[web.1]: [Wed Jun 21 2017 11:40:38 GMT+0000 (UTC)] INFO /app/scripts/trello-integration.js is using deprecated documentation syntax
2017-06-21T11:40:38.306701+00:00 app[web.1]: [Wed Jun 21 2017 11:40:38 GMT+0000 (UTC)] INFO /app/scripts/trello-token.js is using deprecated documentation syntax
2017-06-21T11:40:38.307490+00:00 app[web.1]: [Wed Jun 21 2017 11:40:38 GMT+0000 (UTC)] INFO /app/scripts/trello-webhooks.js is using deprecated documentation syntax
2017-06-21T11:40:38.307977+00:00 app[web.1]: [Wed Jun 21 2017 11:40:38 GMT+0000 (UTC)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.
2017-06-21T11:40:38.307979+00:00 app[web.1]: 
2017-06-21T11:40:38.307980+00:00 app[web.1]: Your hubot-scripts.json is empty, so you just need to remove it.
2017-06-21T11:40:39.055871+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web-url | cut -d= -f2)`
2017-06-21T11:40:39.367976+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] INFO hubot-redis-brain: Discovered redis from REDISCLOUD_URL environment variable
2017-06-21T11:40:39.628102+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] INFO hubot-redis-brain: Successfully authenticated to Redis
2017-06-21T11:40:39.643294+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
2017-06-21T11:40:39.644870+00:00 app[web.1]: hubot env bootstrap did nothing against empty data in redis
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-06-21T11:40:38.305634+00:00 app[web.1]: [Wed Jun 21 2017 11:40:38 GMT+0000 (UTC)] INFO /app/scripts/trello-integration.js is using deprecated documentation syntax
2017-06-21T11:40:38.306701+00:00 app[web.1]: [Wed Jun 21 2017 11:40:38 GMT+0000 (UTC)] INFO /app/scripts/trello-token.js is using deprecated documentation syntax
2017-06-21T11:40:38.307490+00:00 app[web.1]: [Wed Jun 21 2017 11:40:38 GMT+0000 (UTC)] INFO /app/scripts/trello-webhooks.js is using deprecated documentation syntax
2017-06-21T11:40:38.307977+00:00 app[web.1]: [Wed Jun 21 2017 11:40:38 GMT+0000 (UTC)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.
2017-06-21T11:40:38.307979+00:00 app[web.1]: 
2017-06-21T11:40:38.307980+00:00 app[web.1]: Your hubot-scripts.json is empty, so you just need to remove it.
2017-06-21T11:40:39.055871+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web-url | cut -d= -f2)`
2017-06-21T11:40:39.367976+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] INFO hubot-redis-brain: Discovered redis from REDISCLOUD_URL environment variable
2017-06-21T11:40:39.628102+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] INFO hubot-redis-brain: Successfully authenticated to Redis
2017-06-21T11:40:39.643294+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
2017-06-21T11:40:39.644870+00:00 app[web.1]: hubot env bootstrap did nothing against empty data in redis
2017-06-21T11:42:38.981857+00:00 heroku[router]: at=info method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=1d975c85-a705-4d2c-8925-b225c53b6826 fwd="192.30.252.45" dyno=web.1 connect=3ms service=32ms status=200 bytes=216 protocol=https
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-06-21T11:40:38.306701+00:00 app[web.1]: [Wed Jun 21 2017 11:40:38 GMT+0000 (UTC)] INFO /app/scripts/trello-token.js is using deprecated documentation syntax
2017-06-21T11:40:38.307490+00:00 app[web.1]: [Wed Jun 21 2017 11:40:38 GMT+0000 (UTC)] INFO /app/scripts/trello-webhooks.js is using deprecated documentation syntax
2017-06-21T11:40:38.307977+00:00 app[web.1]: [Wed Jun 21 2017 11:40:38 GMT+0000 (UTC)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.
2017-06-21T11:40:38.307979+00:00 app[web.1]: 
2017-06-21T11:40:38.307980+00:00 app[web.1]: Your hubot-scripts.json is empty, so you just need to remove it.
2017-06-21T11:40:39.055871+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web-url | cut -d= -f2)`
2017-06-21T11:40:39.367976+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] INFO hubot-redis-brain: Discovered redis from REDISCLOUD_URL environment variable
2017-06-21T11:40:39.628102+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] INFO hubot-redis-brain: Successfully authenticated to Redis
2017-06-21T11:40:39.643294+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
2017-06-21T11:40:39.644870+00:00 app[web.1]: hubot env bootstrap did nothing against empty data in redis
2017-06-21T11:42:38.981857+00:00 heroku[router]: at=info method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=1d975c85-a705-4d2c-8925-b225c53b6826 fwd="192.30.252.45" dyno=web.1 connect=3ms service=32ms status=200 bytes=216 protocol=https
2017-06-21T11:42:50.956670+00:00 heroku[router]: at=info method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=15df1083-2094-4711-aff0-c9386eddcbdb fwd="192.30.252.45" dyno=web.1 connect=1ms service=5ms status=200 bytes=216 protocol=https
2017-06-21T11:43:17.136297+00:00 heroku[router]: at=info method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=811ff1be-78eb-455b-9cef-721e5cb0b998 fwd="192.30.252.41" dyno=web.1 connect=1ms service=5ms status=200 bytes=216 protocol=https
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-06-21T11:40:38.307977+00:00 app[web.1]: [Wed Jun 21 2017 11:40:38 GMT+0000 (UTC)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.
2017-06-21T11:40:38.307979+00:00 app[web.1]: 
2017-06-21T11:40:38.307980+00:00 app[web.1]: Your hubot-scripts.json is empty, so you just need to remove it.
2017-06-21T11:40:39.055871+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web-url | cut -d= -f2)`
2017-06-21T11:40:39.367976+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] INFO hubot-redis-brain: Discovered redis from REDISCLOUD_URL environment variable
2017-06-21T11:40:39.628102+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] INFO hubot-redis-brain: Successfully authenticated to Redis
2017-06-21T11:40:39.643294+00:00 app[web.1]: [Wed Jun 21 2017 11:40:39 GMT+0000 (UTC)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
2017-06-21T11:40:39.644870+00:00 app[web.1]: hubot env bootstrap did nothing against empty data in redis
2017-06-21T11:42:38.981857+00:00 heroku[router]: at=info method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=1d975c85-a705-4d2c-8925-b225c53b6826 fwd="192.30.252.45" dyno=web.1 connect=3ms service=32ms status=200 bytes=216 protocol=https
2017-06-21T11:42:50.956670+00:00 heroku[router]: at=info method=POST path="/hubot/github-hooks" host=andreasbot.herokuapp.com request_id=15df1083-2094-4711-aff0-c9386eddcbdb fwd="192.30.252.45" dyno=web.1 connect=1ms service=5ms status=200 bytes=216 protocol=https
2017-06-21T11:43:17.136297+00:00 heroku[router]: at=info method=POST path="/hubot/github-hooks" host=andreasbot.

**Comment by ahadjithoma** [comment]
new comment using hubot

**Comment by andreash92** [comment]
hey can i reopen this pls?

**Comment by ahadjithoma** [comment]
testing
